import Foundation
import SwiftData

/// Per-day AI-generated sticky note. Rendered as the masking-tape paper
/// rectangle on the day page (top-right). Generated by Phase 13's Foundation
/// Models pipeline; the user can dismiss to hide.
///
/// One insight per (weekOffset, dayIdx) pair — keyed by `dayKey` so a
/// rolling cache can be cleared by week.
@Model
final class AIInsight {
    @Attribute(.unique) var id: UUID

    /// `"<weekOffset>:<dayIdx>"`, e.g., `"0:5"` for Saturday of the current week.
    @Attribute(.unique) var dayKey: String

    var dateGenerated: Date
    var text: String

    /// Sticky paper color hex. Spec uses `#FFE680` (yellow), `#C9F0E0` (mint),
    /// or `#FFCCC9` (pink), chosen at generation time for variety.
    var colorHex: String

    /// Tilt angle in degrees, typically ±3 to ±5°.
    var tiltDegrees: Double

    var dismissed: Bool

    init(id: UUID = UUID(),
         dayKey: String,
         dateGenerated: Date = .init(),
         text: String,
         colorHex: String = "#FFE680",
         tiltDegrees: Double = 0,
         dismissed: Bool = false)
    {
        self.id = id
        self.dayKey = dayKey
        self.dateGenerated = dateGenerated
        self.text = text
        self.colorHex = colorHex
        self.tiltDegrees = tiltDegrees
        self.dismissed = dismissed
    }
}

extension AIInsight {
    /// Builds a `dayKey` from week + day indices. Both Monday-based.
    static func key(weekOffset: Int, dayIdx: Int) -> String {
        "\(weekOffset):\(dayIdx)"
    }
}
